development:
  cloud_name: furniture
  api_key: '666764451884452'
  api_secret: 1zQzu4MXhHGva8qVgPrHtXWaVUQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: furniture
  api_key: '666764451884452'
  api_secret: 1zQzu4MXhHGva8qVgPrHtXWaVUQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: furniture
  api_key: '666764451884452'
  api_secret: 1zQzu4MXhHGva8qVgPrHtXWaVUQ
  enhance_image_tag: true
  static_image_support: false